### ISSUE TITLE
Minor corrections in the README.md

### ISSUE THREAD

**Issue by klonos** [gifad/references_dialog#1]
I realize that this is done with good intentions and that the text was copy-pasted from the original project in d.org, but using third person feminine pronouns is considered as sexist as using masculine pronouns*. So this:

> This allows for a workflow where the user can create all the references to a node at the same time as **she is** creating it...

...should instead be:

> This allows for a workflow where the user can create all the references to a node at the same time as **they are** creating it...

...and to be more precise on the actual meaning of the sentence:

> This allows for a workflow where **users** can create **any** ~~all the~~ references ~~to a node~~ at the same time ~~as~~ **they are** creating ~~it~~ a node...

More information on the matter:

[Singular they - Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Singular_they):

> **Singular they** is the use in English of the pronoun [they](https://en.wikipedia.org/wiki/They), or its [inflected](https://en.wikipedia.org/wiki/Inflection) or derivative forms, such as them, their, themself, or themselves, as a gender-neutral pronoun to refer to a single person...
> ...
> ...Its use in formal English has increased with the trend toward [gender-inclusive language](https://en.wikipedia.org/wiki/Gender-inclusive_language).

[‘He or she’ versus ‘they’ - Oxford Dictionaries](https://www.oxforddictionaries.com/words/he-or-she-versus-they):

> It’s often important to use language which implicitly or explicitly includes both men and women, making no distinction between the genders....
> ...
> In the past, people tended to use the pronouns **he**, **his**, **him**, or **himself**...
> ...
> Today, this approach is seen as outdated and sexist. ...
> ...
> - You can make the relevant noun plural, rewording the sentence as necessary:...

**Comment by ghost** [comment]
It did not even noticed that…

Thanks, fixed, pushed https://github.com/gifad/references_dialog/commit/e50cfaa477c273bdcf3ece35bdf57d02be5a1ce6

**Comment by klonos** [comment]
> It did not even noticed that…

No worries. I'm notorious for that :smile: 

Thanx for fixing it promptly :+1:
