### ISSUE TITLE
Change iframe to dialog approach?

### ISSUE THREAD

**Issue by robertgarrigos** [gifad/references_dialog#14]
As @indigoxela and @herbdool stated here (https://github.com/backdrop-contrib/references_dialog/issues/4#issuecomment-924629258 ) and here (https://github.com/backdrop-contrib/references_dialog/issues/4#issuecomment-925025131) we might want to change the iframe approach to the dialog. I don't have a strong opinion, but I tend to think that it's neater to use the dialog=true approach.

What are your thoughts?

Thanks.

**Comment by indigoxela** [comment]
> What are your thoughts?

Whatever works. :wink: Usually I tend to prefer dialogs over iframes, but there may also be reasons to use an iframe instead.
I have to admit, that I'm currently not using this module, though.

**Comment by robertgarrigos** [comment]
Just looked into this and realized that I had a misunderstanding. This module is using jquery's dialog already, as well core does now. I believe we shouldn't change anything here.
