### ISSUE TITLE
Fatal error with core "Term Reference" fields

### ISSUE THREAD

**Issue by laryn** [gifad/references_dialog#21]
I tried to change the widget on a core "Term Reference" field to "Autocomplete term widget (for References Dialog)" and then trying to save content gives a fatal error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'taxonomy_term_data.vid' in 'where clause': SELECT taxonomy_term_data.`tid` AS `entity_id`, taxonomy_term_data.`vocabulary` AS `bundle`, :entity_type AS `entity_type`, NULL AS `revision_id` FROM {taxonomy_term_data} taxonomy_term_data WHERE (`taxonomy_term_data`.`name` = :db_condition_placeholder_0) AND (`taxonomy_term_data`.`vid` IN (:db_condition_placeholder_1)) ; Array ( [:db_condition_placeholder_0] => Test [:db_condition_placeholder_1] => [:entity_type] => taxonomy_term )

**Comment by robertgarrigos** [comment]
I was looking into this but could not replicate the error. @laryn, do you still have this error?

**Comment by laryn** [comment]
I'll check when I'm back from vacation.

**Comment by laryn** [comment]
Can you limit to a certain vocabulary? That might trigger it.

**Comment by robertgarrigos** [comment]
no luck. no problem. enjoy your vacation :-)

**Comment by robertgarrigos** [comment]
Hi @laryn I just found a deprecated function within the code (taxonomy_term_uri). There is [PR](https://github.com/backdrop-contrib/references_dialog/pull/29) which might fix your issue. Would you like to try out before I merge? Thanks.

**Comment by robertgarrigos** [comment]
Hi @laryn, just hit your error even with my PR. Checking....

**Comment by argiepiano** [comment]
the problem starts with a 
`Warning: Undefined property: TaxonomyVocabulary::$vid in references_dialog_term_reference_autocomplete_validate() (line 822 of /Users/XXX/Sites/localhost/bdtesting/modules/references_dialog/references_dialog.module).`

Which is produced by code in `references_dialog_term_reference_autocomplete_validate()`

This function uses the deprecated `taxonomy_vocabulary_machine_name_load()`, AND uses $vocabulary->vid, which doesn't exist in Backdrop.

**Comment by robertgarrigos** [comment]
Thanks, @argiepiano just found the problem
