### ISSUE TITLE
Fatal error: "_element_validate_integer_positive" not found or invalid function name

### ISSUE THREAD

**Issue by robertgarrigos** [gifad/references_dialog#24]
I've found this fatal error when saving a field after setting the "Add dialog" check
![Tags___Robert_-_Backhub_-_Vivaldi](https://github.com/user-attachments/assets/b1a4a121-9550-46fc-ad43-77eb95b2e38d)

**Comment by robertgarrigos** [comment]
Line 763 of references_dialog.module:

```
'#element_validate' => array('_element_validate_integer_positive'),
```
provably should be:

```
'#element_validate' => array('references_element_validate_integer_positive'),
```

which means references should be added as dependency also.

**Comment by laryn** [comment]
@robertgarrigos See https://docs.backdropcms.org/change-records/element_validate_number-element_validate_integer-and-element_validate_integer_positive-replaced-with-number-form-api-element-type

**Comment by robertgarrigos** [comment]
Thanks for pointing me to that page. I'll make the proper changes.

**Comment by robertgarrigos** [comment]
Just updated the PR

**Comment by argiepiano** [comment]
This is not the right approach to fix this problem. You added a function that's available in another module (references) and then added a dependency, which creates problems for people like #33 who use this module with entityreference - this forces them to install a module they don't need.

A better approach is to replace the `textfield` form element with a `number` form element, which already includes an integer numerical validation, meaning you can get rid of the `#element_validate`.

Can we please revisit this fix and fix the fix? ;-)

**Comment by argiepiano** [comment]
I'm talking about this fix, that was merged recently:
https://github.com/backdrop-contrib/references_dialog/commit/ea13c9b6b8b636c5841402578424b724f69e5485

**Comment by argiepiano** [comment]
Although, sorry, I see that was reverted in the current release. However, the unnecessary dependency was not removed.

**Comment by robertgarrigos** [comment]
fixed
