### ISSUE TITLE
Fatal error when Drupal compatibility layer is off

### ISSUE THREAD

**Issue by argiepiano** [gifad/references_dialog#31]
If you turn the Drupal compatibility layer off (in settings.php), you get a fatal error when editing the field that uses this widget.

`TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "_element_validate_integer_positive" not found or invalid function name in _form_validate() (line 1497 of /Users/XXX/Sites/localhost/bdtesting/core/includes/form.inc).`

The problem is that this module uses the `#element_validate` callback `_element_validate_integer_positive`. This callback is not available in Backdrop. See [change record](https://docs.backdropcms.org/change-records/element_validate_number-element_validate_integer-and-element_validate_integer_positive-replaced-with-number-form-api-element-type).

The solution is to change the form element to type `number`, instead of using `textfield`, and to remove the `#element_validate` callback in `references_dialog_field_widget_settings_form()`

**Comment by robertgarrigos** [comment]
Thanks,. @argiepiano . This is fixed now.

**Comment by robertgarrigos** [comment]
Just checked that the later release works with layer compatibility off.
