### ISSUE TITLE
Dependency to References prohobits module update

### ISSUE THREAD

**Issue by olafgrabienski** [gifad/references_dialog#33]
When I try to update _References Dialog_ from version 1.x-1.0.6 to 1.0.9, `update.php` reports an unresolved dependency regarding the _References_ module. I'm using _References Dialog_ with _Entity Reference_ instead of _References_, so I'm not able to proceed with the update.

What was the reason to [add the dependency](https://github.com/backdrop-contrib/references_dialog/commit/244e43261e27d0dcdbcb86fb62495027336d2b63) to _References_?

**Comment by argiepiano** [comment]
@olafgrabienski, it looks like @robertgarrigos added this dependency because of a fix he did for an inexistent Backdrop validation callback. He used a function provided by the references module. There is a better fix for that problem that avoids this unnecessary dependency. See #24

**Comment by argiepiano** [comment]
I'm talking about this fix, that was merged recently:
https://github.com/backdrop-contrib/references_dialog/commit/ea13c9b6b8b636c5841402578424b724f69e5485

**Comment by argiepiano** [comment]
Actually, that was reverted, but it looks like the dependency was not removed... I may be misinterpreting this.

**Comment by olafgrabienski** [comment]
@argiepiano - Thanks for your input, interesting! Let's see what Robert says.

**Comment by robertgarrigos** [comment]
Yep. fixed.
