### ISSUE TITLE
Error: $(...).size is not a function

### ISSUE THREAD

**Issue by MartinZbozien** [gifad/references_dialog#35]
There is a problem for the search function working properly with the newest JQuery (in my case 3.7.1)

It will return error: _$(...).size is not a function_

[jquery_fix.patch](https://github.com/user-attachments/files/17192105/jquery_fix.patch)

**Comment by argiepiano** [comment]
Great catch. Can you submit a Pull Request instead of attaching a patch?

**Comment by laryn** [comment]
@MartinZbozien 
When you make the PR, double check where one of the changes adds `.length()` instead of `.length`.

**Comment by argiepiano** [comment]
Actually the correct property is `length` (not a `length()` method)

**Comment by laryn** [comment]
@argiepiano Yes, and it's correct 3 out of 4 times in the patch above.

**Comment by MartinZbozien** [comment]
Sorry guys was doing it fast while working on the project. Will fix it tomorrow and do it properly.

**Comment by argiepiano** [comment]
> Yes, and it's correct 3 out of 4 times in the patch above.

Oops, yes, that happens when I read things too quickly - I misread your response. 👓
