### ISSUE TITLE
Undefined property: stdClass::$nid when adding a reference dialog search view

### ISSUE THREAD

**Issue by robertgarrigos** [gifad/references_dialog#37]
When adding a reference dialog search as a list of node titles, everything works fine unless you uncheck the "link this field to the original content" checkbox in the title's config modal. Then this error appears and views doesn't work:

```
Warning: Undefined property: stdClass::$nid a references_dialog_plugin_display->render() (línia 212 de /modules/references_dialog/views/references_dialog_plugin_display.inc).
```

This can be fixed by adding a nid field. Then, even if both fields are shown as plain text, without link to the node, the view works normally.

Seems like this is by design, that the view needs the nid field, even if it is hidden: https://www.drupal.org/project/references_dialog/issues/1309792

**Comment by robertgarrigos** [comment]
Provably this would need some better documentation....

**Comment by robertgarrigos** [comment]
Working on some documentation in the wiki

**Comment by robertgarrigos** [comment]
I added a [wiki page](https://github.com/backdrop-contrib/references_dialog/wiki) to explain how the search button works. But also I had to create a PR to make it work, as there was some outdated javascript and some module functions were also missing.

**Comment by olafgrabienski** [comment]
@robertgarrigos Thanks for the PR! I have never used the References Dialog search link before (neither in Drupal). However, with help of the wiki page I was able to configure the link and to test the fix. After applying the PR, the Search link works at first sight, at least somehow: When I click the Search link, I see the results of my view in a modal window. When I click one of the results, the modal gets closed and the result gets inserted in the reference field. So, this works.

I'm however not sure how the search is exactly supposed to work. Strangely, there is an "Apply" button in the modal (see screenshot below). Is this button supposed to do anything?

Screenshot:
![image](https://github.com/user-attachments/assets/ece91491-8070-413c-8d4b-b46f1a720586)

**Comment by olafgrabienski** [comment]
Another note: Even if the Search link is working, I get a warning in DBlog:

> Undefined variable $page_bottom in include() (line 51 of core/modules/system/templates/page.tpl.php).

Referrer is the node edit form. PHP version on the test site is 8.1.30.

**Comment by robertgarrigos** [comment]
Thanks, @olafgrabienski, for taking the time to look at it. 

The apply button is of the exposed filters when you add them. It shouldn't be there without filters, of course.

I think I know what is about the warning. I'll take a look.

**Comment by robertgarrigos** [comment]
Fixed on the PR the DB error about $page_bottom and the  "apply" button showing when there is not exposed filters.

**Comment by olafgrabienski** [comment]
Great, both fixes work for me!
