### ISSUE TITLE
Maintaining the project

### ISSUE THREAD

**Issue by herbdool** [gifad/references_dialog#5]
The user who originally ported this module is no longer on github, so I assume this project is abandoned. I've tested it and it works well enough so I'm going to create a real release and update the README.

**Comment by robertgarrigos** [comment]
It works, indeed. I'm using it and will be happy to take over the maintenance of this module.

**Comment by robertgarrigos** [comment]
Added a PR (https://github.com/backdrop-contrib/references_dialog/pull/8) to add myself as maintainer and a new hook to alter the link.

**Comment by herbdool** [comment]
@robertgarrigos thanks. I think protocol is to give it two weeks but since the person who ported is no longer on github I think it's safe to adopt it.

However, I think it's better to split this into two PRs: one just for updating the README to add your name.

**Comment by robertgarrigos** [comment]
ok. will do that.

**Comment by robertgarrigos** [comment]
@herbdool done. Left only the readme changes. Would you like to merge it yourself?

**Comment by herbdool** [comment]
@robertgarrigos done!
